name: app
publish_to: none
version: 2.0.0+22

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1

  stream_chat_flutter: ^9.17.0
  stream_chat_localizations: ^9.17.0
  stream_chat_persistence: ^9.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  go_router_builder: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/view/
    - assets/images/home/
    - assets/images/vip/

######################################
# dart run icons_launcher:create
######################################
icons_launcher:
  image_path: "assets/build/ic_launcher.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    windows:
      enable: true

#######################################
# dart run flutter_native_splash:create
#######################################
flutter_native_splash:
  color: "#f7f6f1"
  image: "assets/build/ic_launcher.png"
  android_12:
    image: "assets/build/ic_launcher.png"
    icon_background_color: "#f7f6f1"
  # web: true
