name: app
publish_to: none
version: 2.0.0+22

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # ╔════════════╗
  # ║   common   ║
  # ╚════════════╝
  code_dart:
    path: ../../../code-records/code-flutter/code_dart
  code_widget:
    path: ../../../code-records/code-flutter/code_widget
  core_wrapper:
    path: ../../../code-records/code-flutter/core_wrapper
  json_annotation: ^4.9.0
  retrofit: ^4.7.0
  go_router: ^16.2.1
  shared_preferences: ^2.5.3
  carousel_slider: ^5.1.1
  dio: ^5.9.0
  dio_http_formatter: any
  # ╔════════════╗
  # ║   other    ║
  # ╚════════════╝
  flutter_triple: ^3.0.0
  video_player: ^2.10.0
  financial_chart: ^0.3.4
  flutter_widget_from_html: ^0.17.1
  city_pickers: ^1.3.0
  pretty_qr_code: ^3.5.0
  signature: ^6.3.0
  flutter_html_to_pdf_plus: ^0.3.0
  sentry_flutter: ^9.6.0
  gif_view: ^1.0.3

  stream_chat_flutter: ^9.17.0
  stream_chat_localizations: ^9.17.0
  stream_chat_persistence: ^9.17.0
  flutter_secure_storage: ^9.2.4
  flutter_app_badger:
    git: # https://github.com/g123k/flutter_app_badger/issues/89#issuecomment-1852717043
      url: https://github.com/g123k/flutter_app_badger.git
      ref: 33cbee6
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # ╔════════════╗
  # ║   dart run build_runner build --delete-conflicting-outputs
  # ║   dart run build_runner watch
  # ╚════════════╝
  code_bin:
    path: ../../../code-records/code-flutter/code_bin
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  go_router_builder: ^3.0.1
  flutter_gen_runner: ^5.10.0
  icons_launcher: ^3.0.1
  flutter_native_splash: ^2.4.6
  retrofit_generator: ^10.0.2
  # fastforge: ^0.6.5
  # openapi_generator: ^6.1.0
  # isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/view/
    - assets/images/home/
    - assets/images/vip/

######################################
# dart run icons_launcher:create
######################################
icons_launcher:
  image_path: "assets/build/ic_launcher.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    windows:
      enable: true

#######################################
# dart run flutter_native_splash:create
#######################################
flutter_native_splash:
  color: "#f7f6f1"
  image: "assets/build/ic_launcher.png"
  android_12:
    image: "assets/build/ic_launcher.png"
    icon_background_color: "#f7f6f1"
  # web: true